import React, { useState, useEffect } from 'react';
import { io } from 'socket.io-client';

export default function SaaSDashboard() {
  const [metrics, setMetrics] = useState({
    activeUsers: 120,
    cpuLoad: 28,
    ramUsage: 54,
    totalRevenue: 42850,
    orderCount: 8
  });
  
  const [orders, setOrders] = useState([
    { id: 'tx-8219', product: 'RGB Mekanik Klavye', price: 1250, timestamp: '11:02:14' },
    { id: 'tx-3901', product: 'Ergonomik Kablosuz Mouse', price: 850, timestamp: '10:58:30' },
    { id: 'tx-2412', product: 'Termos 1L', price: 620, timestamp: '10:45:12' }
  ]);

  const [socketStatus, setSocketStatus] = useState('connecting');
  const [aiReport, setAiReport] = useState('');
  const [generatingReport, setGeneratingReport] = useState(false);

  useEffect(() => {
    let socket;
    let fallbackInterval;

    try {
      socket = io('http://localhost:5000', {
        timeout: 4000,
        reconnectionAttempts: 1
      });

      socket.on('connect', () => {
        setSocketStatus('connected');
      });

      socket.on('connect_error', () => {
        console.warn('Socket.io server connection failed, entering fallback simulation mode.');
        setSocketStatus('fallback');
        startFallbackSimulation();
      });

      socket.on('metricsUpdate', (data) => {
        setMetrics(data);
      });

      socket.on('newOrder', (order) => {
        setOrders((prev) => [order, ...prev.slice(0, 19)]);
      });
    } catch (e) {
      console.warn('Socket client creation failed, entering fallback simulation mode.', e);
      setSocketStatus('fallback');
      startFallbackSimulation();
    }

    function startFallbackSimulation() {
      let currentRevenue = 42850;
      let currentOrders = 8;
      let currentActiveUsers = 124;

      fallbackInterval = setInterval(() => {
        currentActiveUsers = Math.max(80, currentActiveUsers + Math.floor(Math.random() * 11) - 5);
        const cpuLoad = Math.floor(Math.random() * 40) + (currentActiveUsers > 130 ? 40 : 15);
        const ramUsage = Math.floor(Math.random() * 10) + 55;

        if (Math.random() < 0.25) {
          const productNames = [
            'Ergonomik Kablosuz Mouse',
            'Termos 1L',
            'Katlanabilir Kamp Sandalyesi',
            'RGB Mekanik Klavye',
            'Kablosuz Kulaküstü Kulaklık',
            'Akıllı Saat Pro'
          ];
          const randomProduct = productNames[Math.floor(Math.random() * productNames.length)];
          const price = Math.floor(Math.random() * 1500) + 200;
          currentRevenue += price;
          currentOrders += 1;

          const newOrder = {
            id: 'tx-' + Math.random().toString(36).substring(2, 6),
            product: randomProduct,
            price,
            timestamp: new Date().toLocaleTimeString('tr-TR')
          };

          setOrders((prev) => [newOrder, ...prev.slice(0, 9)]);
        }

        setMetrics({
          activeUsers: currentActiveUsers,
          cpuLoad,
          ramUsage,
          totalRevenue: currentRevenue,
          orderCount: currentOrders
        });
      }, 3000);
    }

    return () => {
      if (socket) socket.disconnect();
      if (fallbackInterval) clearInterval(fallbackInterval);
    };
  }, []);

  const handleGenerateAIReport = async () => {
    setGeneratingReport(true);
    setAiReport('');

    try {
      const response = await fetch('http://localhost:5000/api/v1/ai/analyze', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ metrics }),
      });

      if (!response.ok) {
        throw new Error('API server returned error status');
      }

      const data = await response.json();
      setAiReport(data.report);
    } catch (error) {
      console.warn('Failed to fetch AI report from server, using client-side AI analysis fallback.');
      await new Promise((resolve) => setTimeout(resolve, 1500));
      
      const localReport = `
# 📊 AI EXECUTIVE REPORT & SYSTEM INSIGHTS / AKILLI YÖNETİCİ ÖZETİ (FALLBACK MODE)
*Generated by client-side AI assistant engine.*

---

## 🇹🇷 Türkçe Analiz Raporu

### 📈 Genel SaaS Metrikleri
- **Toplam Gelir:** ₺${metrics.totalRevenue.toLocaleString('tr-TR')}
- **Toplam Sipariş Adedi:** ${metrics.orderCount} adet
- **Anlık Aktif Kullanıcı:** ${metrics.activeUsers} kullanıcı

### ⚙️ Sistem Sağlık Durumu: ${metrics.cpuLoad > 75 ? '⚠️ YÜKSEK YÜK' : '🟢 KARARLI'}
- **CPU Yükü:** %${metrics.cpuLoad}
- **RAM Kullanımı:** %${metrics.ramUsage}

### 🧠 Botan-AI Akıllı Yorum ve Öneriler
1. **İşletme ve Gelir Performansı:** Toplam ₺${metrics.totalRevenue.toLocaleString('tr-TR')} ciro elde edilmiştir. Ortalama sepet tutarı ₺${(metrics.totalRevenue / (metrics.orderCount || 1)).toFixed(2)} bandındadır.
2. **Kullanıcı Davranış Analizi:** Anlık aktif kullanıcı sayısı (${metrics.activeUsers}) sistem kapasitesi ile uyumludur. Trafik normal seyretmektedir.
3. **Altyapı ve Sistem Tavsiyesi:** CPU Yükü %${metrics.cpuLoad} seviyesindedir. ${metrics.cpuLoad > 75 ? 'İşlemci yükü yüksek, scaling ayarları kontrol edilmelidir.' : 'Kaynaklar ideal, müdahale gerekmemektedir.'}

---

## 🇺🇸 English Executive Report

### 📈 SaaS Core Metrics
- **Total Revenue:** $${(metrics.totalRevenue / 34).toFixed(2)} (Estimated)
- **Total Order Count:** ${metrics.orderCount} orders
- **Active Live Users:** ${metrics.activeUsers} users

### ⚙️ Infrastructure & Health: ${metrics.cpuLoad > 75 ? '⚠️ HIGH LOAD' : '🟢 STABLE'}
- **CPU Load:** ${metrics.cpuLoad}%
- **RAM Usage:** ${metrics.ramUsage}%

### 🧠 Botan-AI Insights & Actions
1. **Business Performance:** Transactional stream is stable with $${(metrics.totalRevenue / 34).toFixed(2)} total revenue.
2. **User Traffic Trends:** Live user count is currently at ${metrics.activeUsers}.
3. **Infrastructure Advisory:** CPU utilization is ${metrics.cpuLoad}%. ${metrics.cpuLoad > 75 ? 'Critical load observed, verify server resources.' : 'Stable health, no actions required.'}
      `;
      setAiReport(localReport.trim());
    } finally {
      setGeneratingReport(false);
    }
  };

  return (
    <div style={{ padding: '2rem 1.5rem', minHeight: 'calc(100vh - 80px)', color: 'var(--text-main)', display: 'flex', flexDirection: 'column', gap: '2rem' }}>
      
      {/* Header and Connection Status */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <h1 style={{ fontSize: '2rem', fontWeight: '800', margin: 0, background: 'linear-gradient(135deg, var(--accent-purple), var(--accent-cyan))', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
            Real-Time SaaS Dashboard
          </h1>
          <p style={{ margin: '0.3rem 0 0 0', color: 'var(--text-muted)', fontSize: '0.9rem' }}>
            Socket.io canlı veri akışı ve yapay zeka analiz platformu.
          </p>
        </div>
        
        {/* Status Badge */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '6px 14px', borderRadius: '20px', background: 'rgba(255, 255, 255, 0.03)', border: '1px solid var(--border-color)', fontSize: '0.85rem', fontWeight: '600' }}>
          <span style={{
            width: '8px',
            height: '8px',
            borderRadius: '50%',
            backgroundColor: socketStatus === 'connected' ? '#10b981' : socketStatus === 'fallback' ? '#f59e0b' : '#ef4444',
            boxShadow: socketStatus === 'connected' ? '0 0 8px #10b981' : socketStatus === 'fallback' ? '0 0 8px #f59e0b' : '0 0 8px #ef4444'
          }} />
          {socketStatus === 'connected' ? 'Socket: Canlı (Connected)' : socketStatus === 'fallback' ? 'Socket: Fallback (Simülasyon)' : 'Soket Bağlanıyor...'}
        </div>
      </div>

      {/* Metric Cards Grid */}
      <div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '1.2rem' }}>
        
        {/* Revenue */}
        <div className="card animate-fadeIn" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
          <div>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', textTransform: 'uppercase', fontWeight: 'bold' }}>Toplam Gelir / Revenue</span>
            <h2 style={{ fontSize: '2rem', fontWeight: '800', margin: '0.4rem 0' }}>
              ₺{metrics.totalRevenue.toLocaleString('tr-TR')}
            </h2>
          </div>
          <div style={{ fontSize: '0.8rem', color: 'var(--accent-cyan)', fontWeight: 'bold' }}>
            📈 Son işlemler dahil
          </div>
        </div>

        {/* Active Users */}
        <div className="card animate-fadeIn" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
          <div>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', textTransform: 'uppercase', fontWeight: 'bold' }}>Aktif Kullanıcılar / Active</span>
            <h2 style={{ fontSize: '2rem', fontWeight: '800', margin: '0.4rem 0', color: 'var(--accent-purple)' }}>
              {metrics.activeUsers}
            </h2>
          </div>
          <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
            👥 Canlı veri simülasyonu (3s)
          </div>
        </div>

        {/* CPU Load */}
        <div className="card animate-fadeIn" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
          <div>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', textTransform: 'uppercase', fontWeight: 'bold' }}>CPU Yükü / Processor</span>
            <h2 style={{ fontSize: '2rem', fontWeight: '800', margin: '0.4rem 0', color: metrics.cpuLoad > 75 ? '#ef4444' : 'var(--text-main)' }}>
              %{metrics.cpuLoad}
            </h2>
          </div>
          <div style={{ width: '100%', height: '4px', backgroundColor: 'rgba(255, 255, 255, 0.05)', borderRadius: '2px', overflow: 'hidden' }}>
            <div style={{
              width: `${metrics.cpuLoad}%`,
              height: '100%',
              backgroundColor: metrics.cpuLoad > 75 ? '#ef4444' : 'var(--accent-cyan)',
              transition: 'width 0.5s ease-in-out'
            }} />
          </div>
        </div>

        {/* RAM Usage */}
        <div className="card animate-fadeIn" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
          <div>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', textTransform: 'uppercase', fontWeight: 'bold' }}>RAM Kullanımı / Memory</span>
            <h2 style={{ fontSize: '2rem', fontWeight: '800', margin: '0.4rem 0' }}>
              %{metrics.ramUsage}
            </h2>
          </div>
          <div style={{ width: '100%', height: '4px', backgroundColor: 'rgba(255, 255, 255, 0.05)', borderRadius: '2px', overflow: 'hidden' }}>
            <div style={{
              width: `${metrics.ramUsage}%`,
              height: '100%',
              backgroundColor: 'var(--accent-purple)',
              transition: 'width 0.5s ease-in-out'
            }} />
          </div>
        </div>

      </div>

      {/* Main Section: Live Streams & AI Analytics */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem', alignItems: 'start' }}>
        
        {/* Left Column: Live Order Stream */}
        <div className="card" style={{ display: 'flex', flexDirection: 'column', gap: '1rem', minHeight: '400px' }}>
          <h3 style={{ fontSize: '1.2rem', fontWeight: '700', margin: 0, borderBottom: '1px solid var(--border-color)', paddingBottom: '0.5rem' }}>
            Canlı İşlem Akışı / Real-time Logs
          </h3>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.8rem', maxHeight: '320px', overflowY: 'auto', paddingRight: '4px' }}>
            {orders.length === 0 ? (
              <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', textAlign: 'center', marginTop: '2rem' }}>Sipariş akışı bekleniyor...</p>
            ) : (
              orders.map((o) => (
                <div key={o.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '10px 14px', borderRadius: '10px', background: 'rgba(255, 255, 255, 0.02)', border: '1px solid var(--border-color)', fontSize: '0.9rem' }}>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '2px' }}>
                    <span style={{ fontWeight: 'bold' }}>{o.product}</span>
                    <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>ID: {o.id} | Saat: {o.timestamp}</span>
                  </div>
                  <span style={{ color: 'var(--accent-cyan)', fontWeight: 'bold' }}>+₺{o.price}</span>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Right Column: AI Analysis */}
        <div className="card" style={{ display: 'flex', flexDirection: 'column', gap: '1.2rem', minHeight: '400px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--border-color)', paddingBottom: '0.5rem' }}>
            <h3 style={{ fontSize: '1.2rem', fontWeight: '700', margin: 0 }}>
              AI Rapor Üreticisi / AI Insights
            </h3>
            <button 
              onClick={handleGenerateAIReport}
              disabled={generatingReport}
              className="btn btn-primary"
              style={{
                padding: '6px 14px',
                fontSize: '0.8rem',
                borderRadius: '8px',
                background: generatingReport ? 'var(--border-color)' : 'linear-gradient(135deg, var(--accent-purple), var(--accent-cyan))',
                color: '#fff',
                cursor: generatingReport ? 'not-allowed' : 'pointer',
                fontWeight: 'bold',
                border: 'none'
              }}
            >
              {generatingReport ? 'Analiz Ediliyor...' : 'AI Raporu Üret ✨'}
            </button>
          </div>

          <div style={{ flex: 1, padding: '12px', borderRadius: '10px', background: 'rgba(0, 0, 0, 0.2)', border: '1px solid var(--border-color)', overflowY: 'auto', maxHeight: '300px', fontSize: '0.85rem', lineHeight: '1.6' }}>
            {generatingReport ? (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '200px', gap: '1rem' }}>
                <div style={{ width: '40px', height: '40px', border: '3px solid rgba(255, 255, 255, 0.1)', borderTopColor: 'var(--accent-purple)', borderRadius: '50%', animation: 'spin 1s linear infinite' }} />
                <style dangerouslySetInnerHTML={{__html: `
                  @keyframes spin {
                    0% { transform: rotate(0deg); }
                    100% { transform: rotate(360deg); }
                  }
                `}} />
                <span style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>Botan-AI verileri analiz ediyor...</span>
              </div>
            ) : aiReport ? (
              <div style={{ whiteSpace: 'pre-line' }}>
                {aiReport}
              </div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '200px', color: 'var(--text-muted)', textAlign: 'center' }}>
                <span style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>🧠</span>
                <p style={{ margin: 0, fontSize: '0.85rem' }}>AI Raporu Üret butonuna tıklayarak metrikleri analiz eden anlık yapay zeka özetini oluşturun.</p>
              </div>
            )}
          </div>
        </div>

      </div>

    </div>
  );
}
